// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcDateService.proto

package com.xiangzi.service;

public interface RpcDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xiangzi.service.api.RpcDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
