// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcDateService.proto

package com.xiangzi.service;

public final class RpcDateServiceApi {
  private RpcDateServiceApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiangzi_service_api_RpcDateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xiangzi_service_api_RpcDateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xiangzi_service_api_RpcDateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xiangzi_service_api_RpcDateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024RpcDateService.proto\022\027com.xiangzi.serv" +
      "ice.api\"\"\n\016RpcDateRequest\022\020\n\010userName\030\001 " +
      "\001(\t\"%\n\017RpcDateResponse\022\022\n\nserverDate\030\001 \001" +
      "(\t2p\n\016RpcDateService\022^\n\007getDate\022\'.com.xi" +
      "angzi.service.api.RpcDateRequest\032(.com.x" +
      "iangzi.service.api.RpcDateResponse\"\000B*\n\023" +
      "com.xiangzi.serviceB\021RpcDateServiceApiP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_xiangzi_service_api_RpcDateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xiangzi_service_api_RpcDateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xiangzi_service_api_RpcDateRequest_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_com_xiangzi_service_api_RpcDateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xiangzi_service_api_RpcDateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xiangzi_service_api_RpcDateResponse_descriptor,
        new java.lang.String[] { "ServerDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
