// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcDateService.proto

package com.xiangzi.service;

public interface RpcDateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xiangzi.service.api.RpcDateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverDate = 1;</code>
   * @return The serverDate.
   */
  java.lang.String getServerDate();
  /**
   * <code>string serverDate = 1;</code>
   * @return The bytes for serverDate.
   */
  com.google.protobuf.ByteString
      getServerDateBytes();
}
